---
- name: update system
  apt: 
    update_cache: yes
    cache_valid_time: 3600

- name: upgrade all packages
  apt: 
    name: "*"
    state: latest

- name: check kafka file for skipp step 
  stat: path=/tmp/kafka_2.12-{{ version_kafka }}.tgz
  register: file_check_kafka

- name: install Java OpenJDK 11
  apt: 
     name: default-jdk
     state: latest

- name: create user kafka
  user:
    name: kafka 
    state: present 
    shell: /bin/false
    create_home: false 

- name: Dowland packer kafka https://dlcdn.apache.org/kafka/{{ version_kafka }}/kafka_2.12-{{ version_kafka }}.tgz
  get_url:
    url: https://dlcdn.apache.org/kafka/{{ version_kafka }}/kafka_2.12-{{ version_kafka }}.tgz
    dest: /tmp/
    # checksum: "sha512:https://dlcdn.apache.org/kafka/{{ version_kafka }}/kafka_2.12-{{ version_kafka }}.tgz.sha512"
  when: not file_check_kafka.stat.exists

- name: extract the file kafka
  unarchive:
    src: /tmp/kafka_2.12-{{ version_kafka }}.tgz
    dest: '{{ kafka_path }}'
    remote_src: yes
  when: not file_check_kafka.stat.exists

- name: MV catalog
  command: mv {{ kafka_path }}/kafka_2.12-{{ version_kafka }} /opt/kafka
  when: not file_check_kafka.stat.exists

- name: Create directory ownership  kafka
  file:
    path: '{{ kafka_path }}/kafka/logs'
    state: directory
  when: not file_check_kafka.stat.exists

- name: Default location for Apache Kafka logs to the directory
  lineinfile:
    path: '{{ kafka_path }}/kafka/config/server.properties'
    regexp: 'log.dirs='
    line: 'log.dirs=/opt/kafka/logs'
  when: not file_check_kafka.stat.exists

- name: Create directory ownership  kafka/zookeepe for cluster
  file:
    path: '{{ kafka_path }}/kafka/zookeeper'
    state: directory

- name: Copy config template kafka.service
  template:
    src: kafka.service.j2
    dest: /etc/systemd/system/kafka.service
    owner: root
    group: root
    mode: 0644

- name: Copy config template zookeeper.service
  template:
    src: zookeeper.service.j2
    dest: /etc/systemd/system/zookeeper.service
    owner: root
    group: root
    mode: 0644

- name: Copy template myid
  template:
    src: myid.j2
    dest: '{{ kafka_path }}/kafka/zookeeper/myid'
    owner: root
    group: root
    mode: 0644

- name: Copy template zookeeper.properties
  template:
    src: zookeeper.properties.j2
    dest: '{{ kafka_path }}/kafka/config/zookeeper.properties'
    owner: root
    group: root
    mode: 0644

- name: Copy template server.properties
  template:
    src: server.properties.j2
    dest: '{{ kafka_path }}/kafka/config/server.properties'
    owner: root
    group: root
    mode: 0644

- name: systemd reload
  systemd:
    daemon_reload: True

- name: kafka and zookeeper systemctl enable and start
  systemd:
    name: zookeeper
    state: started
    enabled: true

- name: kafka and zookeeper systemctl enable and start
  systemd:
    name: kafka
    state: started
    enabled: true